import React, { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";
import { AiOutlineArrowRight } from "react-icons/ai";

function bloge() {
  const [blog, setBlog] = useState([]);

  useEffect(() => {
    axios
      .get("https://jsonplaceholder.typicode.com/posts/1/comments")
      .then((res) => {
        setBlog(res.data);
      });
  }, []);

  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
          <div class="flex flex-wrap -m-4">
            {blog.map((value) => (
              <div key={value.id} class="p-4 lg:w-1/3">
                <div class="h-full bg-gray-100 bg-opacity-75 px-8 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
                  <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">
                    {value.name}
                  </h1>
                  <p class="leading-relaxed mb-3">{value.body}</p>
                  <a class="text-indigo-500 inline-flex items-center">
                    Learn More
                    <samp className="ml-2">
                      <AiOutlineArrowRight />
                    </samp>
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}

export default bloge;
